# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChatgptTui < Formula
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.7.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0/chatgpt-tui_0.7.0_darwin_arm64.zip"
    sha256 "ba0688e5d605fc1823ec720b3cbf97aa8874a1f901dc54125263eddaab67bbfc"

    def install
      bin.install "bin/chatgpt-tui"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0/chatgpt-tui_0.7.0_darwin_amd64.zip"
    sha256 "28c55a90479ab9efd41786e0ce813c41bc9ed168dec8b3c2dc9d711a7751a8ed"

    def install
      bin.install "bin/chatgpt-tui"
    end
  end

  def post_install
    opoo "⚠︎ chatgpt-tui is deprecated and will be removed in the future. Use nekot instead."
  end
end
