# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nekot < Formula
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.7.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0/nekot_0.7.0_darwin_arm64.zip"
    sha256 "6028cefda473752e8455eb5175412f1259cd56843fec48f168f7fbcca3b4d546"

    def install
      bin.install "bin/nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0/nekot_0.7.0_darwin_amd64.zip"
    sha256 "361d75432d62a99e68520d50594936aa193737a5b421ab0505efe49548168fec"

    def install
      bin.install "bin/nekot"
    end
  end
end
