# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RcChatgptTui < Formula
  desc ""
  homepage "https://github.com/BalanceBalls/chatgpt-tui"
  version "0.7.0-rc"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0-rc/nekot_0.7.0-rc_darwin_arm64.zip"
    sha256 "d3575b3c92d2d2660a68d5eb3344a723b36fa44a8ae5cc57ee63f1e2d0de2299"

    def install
      bin.install "bin/rc-chatgpt-tui"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0-rc/nekot_0.7.0-rc_darwin_amd64.zip"
    sha256 "d3f738a2b3afb0d488a64d69601befb67da0f3a907675b10abe08ae2d2488efa"

    def install
      bin.install "bin/rc-chatgpt-tui"
    end
  end

  def post_install
    opoo "⚠︎ rc-chatgpt-tui is deprecated and will be removed in the future. Use rc-nekot instead."
  end
end
