# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RcNekot < Formula
  desc ""
  homepage "https://github.com/BalanceBalls/chatgpt-tui"
  version "0.7.1-rc"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc/rc-nekot_nekot_0.7.1-rc_darwin_arm64.zip"
    sha256 "87134c8c7ccbb4714e307d3ba8f84c90249a78019d62ff18b6ba553e04534b8e"

    def install
      bin.install "bin/rc-nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc/rc-nekot_nekot_0.7.1-rc_darwin_amd64.zip"
    sha256 "f935a27de1ba136abf073564e21ef2e435b023ce7f2dd62bd34407d29a2cb526"

    def install
      bin.install "bin/rc-nekot"
    end
  end
end
