# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RcNekot < Formula
  desc ""
  homepage "https://github.com/BalanceBalls/chatgpt-tui"
  version "0.7.0-rc"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0-rc/rc-nekot_nekot_0.7.0-rc_darwin_arm64.zip"
    sha256 "b347a766759601cf21bc1b996c946e199431e1383d0d6cce03093d5dd38911f7"

    def install
      bin.install "bin/rc-nekot"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.0-rc/rc-nekot_nekot_0.7.0-rc_darwin_amd64.zip"
    sha256 "08b489c9ab5c6be6c3370839982cce46af12d4a13aeaaf207a93c8109dfa1089"

    def install
      bin.install "bin/rc-nekot"
    end
  end
end
