# This file was generated by GoReleaser. DO NOT EDIT.
cask "nekot" do
  name "nekot"
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.8.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nekot"

  on_macos do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v#{version}/nekot_#{version}_darwin_amd64.tar.gz"
      sha256 "b45df29bc05fae48a243c05ca602f6838f3e8cb8b8d72d410dbfc2ef842678a8"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v#{version}/nekot_#{version}_darwin_arm64.tar.gz"
      sha256 "58845a961d76e883c4cde31e561d7780290de54c5b9bb2c0f64e26399c918c00"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v#{version}/nekot_#{version}_linux_amd64.tar.gz"
      sha256 "c6630e7da1a79f93f5037e0eb0e268ae3010a3631dd9b85aae4726b2956bdaa0"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v#{version}/nekot_#{version}_linux_arm64.tar.gz"
      sha256 "5b1a8f015bb201842c5d573b5f975b9192f269760a8fd1490e15f27faac19731"
    end
  end

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/nekot"]
      end
    end
  end

  # No zap stanza required
end
