# This file was generated by GoReleaser. DO NOT EDIT.
cask "nekot" do
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.7.6"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nekot"

  on_macos do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.6/nekot_0.7.6_darwin_amd64.tar.gz"
      sha256 "b15573dc361f79a3d62a1ef5996cdb0b2c9aa4297ffd1e7321f3832afc0314be"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.6/nekot_0.7.6_darwin_arm64.tar.gz"
      sha256 "35295e99e2f94f9ff2be7da1016d3ec365d4ecfe833f1b20547f078635f1bbc8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.6/nekot_0.7.6_linux_amd64.tar.gz"
      sha256 "5d85d24b7125dcd01a56917a6d8cb654384ceeb7cd1050fd739026ce89614809"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.6/nekot_0.7.6_linux_arm64.tar.gz"
      sha256 "f3b1f54bf4ccebb073286596ea9f9389b677ed46ae4bcff1390f35561f71c85e"
    end
  end

  conflicts_with formula: [
      "nekot",
    ]

  postflight do
    if OS.mac?
      if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
        system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/nekot"]
      end
    end
  end

  # No zap stanza required
end
