# This file was generated by GoReleaser. DO NOT EDIT.
cask "nekot" do
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nekot"

  on_macos do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1/nekot_0.7.1_darwin_amd64.tar.gz"
      sha256 "64098ff03077e369d4353c9833047e4d1bc72ffbe0663ca3f8be1e7b9b5d30a5"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1/nekot_0.7.1_darwin_arm64.tar.gz"
      sha256 "5b5a6da92d353378a469a02a6def089f9942ae84f553df19a2d7d2d10420f0c6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1/nekot_0.7.1_linux_amd64.tar.gz"
      sha256 "67a204babb06a5f1f8021ba6a90e63a9ae014a3fb123e6d29d6b2a3b88dadd72"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1/nekot_0.7.1_linux_arm64.tar.gz"
      sha256 "45be791ca1336ca10b201b67c251950600ba11e9334c2113ca8f394c8f426d73"
    end
  end

  conflicts_with formula: [
      "nekot",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/nekot"]
    end
  end

  # No zap stanza required
end
