# This file was generated by GoReleaser. DO NOT EDIT.
cask "rc-nekot" do
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.7.2-rc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rc-nekot"

  on_macos do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.2-rc/nekot_0.7.2-rc_darwin_amd64.tar.gz"
      sha256 "2870ad543605768278d9a434597d05362f2e12e28298ecdb8d2dd355e218dca0"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.2-rc/nekot_0.7.2-rc_darwin_arm64.tar.gz"
      sha256 "68355adeebad21b4d8a0be78f6ef10d2853ff17b4c446ea68feb74e62f763d99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.2-rc/nekot_0.7.2-rc_linux_amd64.tar.gz"
      sha256 "3c49e8b47e7af06e6525e0a234b63fdabc1b4a4b676a11041d84bfad12f4942b"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.2-rc/nekot_0.7.2-rc_linux_arm64.tar.gz"
      sha256 "015deccfad0b4bccc00e54283a012d2e187d69244167feeac83d6cf7c999423b"
    end
  end

  conflicts_with formula: [
      "rc-nekot",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/rc-nekot"]
    end
  end

  # No zap stanza required
end
