# This file was generated by GoReleaser. DO NOT EDIT.
cask "rc-nekot" do
  desc ""
  homepage "https://github.com/BalanceBalls/chatgpt-tui"
  version "0.7.1-rc10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rc-nekot"

  on_macos do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc10/nekot_0.7.1-rc10_darwin_amd64.tar.gz"
      sha256 "c7022fc878d43361627b55b7532b8b00f0aaf08683d3404943d09c7aafbc6247"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc10/nekot_0.7.1-rc10_darwin_arm64.tar.gz"
      sha256 "ad2bc2d2bcd8b068999cacb6a415fa33aed4d73cceaa8407b7fb86247b7e5348"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc10/nekot_0.7.1-rc10_linux_amd64.tar.gz"
      sha256 "9ced626a60e355211a5cfd41bd936561622b28339139659547c220846f4155d6"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc10/nekot_0.7.1-rc10_linux_arm64.tar.gz"
      sha256 "c41e1af18aafd070dc966f63887213756c25b1f9af0058ea5d0a3706c29e06ba"
    end
  end

  # No zap stanza required
end
