# This file was generated by GoReleaser. DO NOT EDIT.
cask "rc-nekot" do
  desc ""
  homepage "https://github.com/BalanceBalls/nekot"
  version "0.7.1-rc12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rc-nekot"

  on_macos do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc12/nekot_0.7.1-rc12_darwin_amd64.tar.gz"
      sha256 "799122244729d055083c5383d2e377e433dd9376bd3810020740162f0b12999a"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc12/nekot_0.7.1-rc12_darwin_arm64.tar.gz"
      sha256 "ba6654ec665303a6fcb0d9d3795413790e0329b2729be548dc127711ee0bc9cf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc12/nekot_0.7.1-rc12_linux_amd64.tar.gz"
      sha256 "5be9b61b015908a94cec3180734fde07de597515babad0b6e36bc895ff4dfb44"
    end
    on_arm do
      url "https://github.com/BalanceBalls/nekot/releases/download/v0.7.1-rc12/nekot_0.7.1-rc12_linux_arm64.tar.gz"
      sha256 "6d4d18e51c615d9c273a1049c050ce371c0d52520af72fa4610a381324c65ae5"
    end
  end

  conflicts_with formula: [
      "rc-nekot",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/rc-nekot"]
    end
  end

  # No zap stanza required
end
